# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NKOtYDZcqJI40-Ca_7xo5wq7oDQvRTWo
"""

import numpy as np
import matplotlib.pyplot as plt

# X o'qlaridagi nuqtalar (0 dan 2*pi gacha)
x = np.linspace(0, 2 * np.pi, 1000)

# Sinus funksiyasi
y = np.sin(x)

# Grafigi chizish
plt.plot(x, y)

# Grafikni bezash
plt.title('Sinus funksiyasining grafigi')
plt.xlabel('X')
plt.ylabel('Y = sin(x)')

# Grafigni ko'rsatish
plt.grid(True)
plt.show()